global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'l0-app'
    static_configs:
      - targets: ['app:8080']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
